[project]
name = "mtto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "pylance>=0.39.0",
    "python-dotenv>=1.2.1",
]
